# Site settings
title: Cocktail Insights
header-img: img/dashboard1.jpg
email: your-email@yourdomain.com
copyright_name: CockTail Insights
description: "Helping eCommerce businesses maximise social media ROI"
baseurl: ""
url: ""
twitter_username: cocktailinsight
facebook_username:  cocktailinsights
email_username:  team@Cocktailinsights.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
