<<<<<<< HEAD
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
=======
# Site settings
title: Cocktail Insights
header-img: img/dashboard1.jpg
email: your-email@yourdomain.com
copyright_name: Cocktail Insights
description: "Helping eCommerce businesses maximise social media ROI"
baseurl: "http://Cocktailinsights.github.io/blog/"
url: ""
twitter_username: cocktailinsight
github_username:  davidtmiller
facebook_username:  cocktailinsights
email_username:  team@cocktailinsights.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
>>>>>>> origin/gh-pages
