# Site settings
title: Cocktail Insights
header-img: img/dashboard1.jpg
email: your-email@yourdomain.com
copyright_name: Cocktail Insights
description: "Helping eCommerce businesses maximise social media ROI"
baseurl: "cocktailinsights.github.io/blog/"
url: ""
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  IronSummitMedia
email_username:  team@Cocktailinsights.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
